- Added images, Brief explanation of ScalingManager
maplelabs/opensearch-scaling-manager pull request #422
Opened 2023-03-03 06:31 UTC by Manojkumar-Chandru-ML

2023-03-03 17:10 UTC, Akhil-Nair-ML requested changes
Give an example for launch template id.
Today our end user tried to give name instead id.
They got following error:
<html>
<body>
<!--StartFragment-->

InvalidLaunchTemplateId.Malformed | The ID for the launch template is malformed. Ensure that you specify the launch template ID in the form lt-xxxxxxxxxxxxxxxxx.
-- | --


<!--EndFragment-->
</body>
</html>
Give an example of id as above.

2023-03-06 05:34 UTC, Siddharth-Rai-ML requested changes

2023-03-06 05:34 UTC, Siddharth-Rai-ML commented on README.md
Please add a description of what Scaling Manager is and what are the features build in it

2023-03-06 11:58 UTC, Siddharth-Rai-ML approved these changes

2023-03-07 06:02 UTC, merged