Custom error for validation failure.
maplelabs/opensearch-scaling-manager pull request #93
Opened 2022-12-14 06:48 UTC by Manojkumar-Chandru-ML

Created ValidationError class inside errors.py to reraise exceptions occurring during validation of config.yaml.
Resolves #92

2022-12-14 09:33 UTC, Siddharth-Rai-ML requested changes
Please have a look

2022-12-14 09:33 UTC, Siddharth-Rai-ML commented on simulator/src/config_parser.py
>  class Config:
there should always be 2 empty lines before class definition

2022-12-14 09:33 UTC, Siddharth-Rai-ML commented on simulator/src/config_parser.py
> +        raise ValidationError(str(e))
sys.stdout.write(e) can be removed, all the messages can be combined and raised as ValidationError.

eg. ValidationError('error reading config file - ' + str(e))

2022-12-14 09:33 UTC, Siddharth-Rai-ML commented on simulator/src/errors.py
> +    pass
Add an empty line the end of file

2022-12-14 09:33 UTC, Siddharth-Rai-ML commented on simulator/src/config_parser.py
> +        raise ValidationError(str(e))
There is no variable called e

Here it should be:

ValidationError('Error validating config file - ' + str(errors))

sys.stdout can be removed

2022-12-14 09:33 UTC, Siddharth-Rai-ML commented on simulator/src/errors.py
> +    pass
Add docstring:

"""Raised when errors are encountered in cofig file validation"""

2022-12-16 05:43 UTC, Manojkumar-Chandru-ML commented on simulator/src/errors.py
> +    pass
I have added extra line

2022-12-16 05:45 UTC, Akhil-Nair-ML commented
LGTM

2022-12-16 05:45 UTC, merged